name: artifact test

on:
  push:
    branches:

  env:
    ARTIFACT_NAME: hello-world
  steps:
    - build:
        runs-on: ubuntu-latest
        
    - name: checkout
      uses: actions/checkout@v2

    - name: Create file with echo
      run: echo "Hello world" > hello.txt

    - name: upload artifact
      uses: actions/upload-artifact@2
      with:
        - name: ${{ env.ARTIFACT_NAME }} 
          path: hello.txt

