name: first

on: push

jobs:
  ubuntu-job: 
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: echo $(date)

  windows-job:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: Get-Date 

  mac-job: 
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: echo $(date)


  final-job: 
    name: First job
    runs-on: ubuntu-latest
    needs: [ubuntu-job, windows-job, mac-job]
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: echo $(date)
